-- ============================================================================
-- SmartResumeAI — Supabase schema (source of truth)
-- Run once in the Supabase SQL Editor (Dashboard -> SQL -> New query -> Run).
-- Idempotent: safe to re-run.
--
-- What this sets up:
--   * public.profiles / public.resumes / public.ats_reports
--   * indexes
--   * Row Level Security so a user can only touch their own rows
--   * a trigger that auto-creates a profile row when a user signs up
--   * the private "resumes" Storage bucket for uploaded files
--
-- Identity lives in auth.users (managed by Supabase Auth). profiles.id === auth.users.id.
-- The FastAPI backend connects as the postgres role (bypasses RLS) and enforces
-- ownership in code; RLS here is defense-in-depth for any direct PostgREST access.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
    id          uuid        primary key references auth.users (id) on delete cascade,
    email       text        not null,
    full_name   text        not null default '',
    username    text        not null unique,
    created_at  timestamptz not null default now()
);

create table if not exists public.resumes (
    id             integer generated by default as identity primary key,
    user_id        uuid        not null references public.profiles (id) on delete cascade,
    title          text        not null default 'My Resume',
    personal_info  jsonb       not null default '{}'::jsonb,
    education      jsonb       not null default '[]'::jsonb,
    skills         jsonb       not null default '[]'::jsonb,
    projects       text        not null default '',
    experience     text        not null default '',
    certifications text        not null default '',
    summary        text        not null default '',
    template_id    text        not null default 'modern',
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);

create table if not exists public.ats_reports (
    id               integer generated by default as identity primary key,
    user_id          uuid        not null references public.profiles (id) on delete cascade,
    resume_id        integer     references public.resumes (id) on delete set null,
    job_description  text        not null default '',
    score            integer     not null default 0,
    grade            text        not null default 'F',
    breakdown        jsonb       not null default '{}'::jsonb,
    matched_keywords jsonb       not null default '[]'::jsonb,
    missing_keywords jsonb       not null default '[]'::jsonb,
    storage_path     text,
    ai_feedback      text        not null default '',
    created_at       timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
create index if not exists idx_resumes_user      on public.resumes (user_id);
create index if not exists idx_ats_user          on public.ats_reports (user_id);
create index if not exists idx_ats_resume        on public.ats_reports (resume_id);
create index if not exists idx_ats_user_created  on public.ats_reports (user_id, created_at desc);

-- keep resumes.updated_at fresh on UPDATE
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists trg_resumes_touch on public.resumes;
create trigger trg_resumes_touch
    before update on public.resumes
    for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.profiles    enable row level security;
alter table public.resumes     enable row level security;
alter table public.ats_reports enable row level security;

-- profiles: a user sees/edits only their own row
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
    for select using (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
    for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
    for insert with check (auth.uid() = id);

-- resumes: full CRUD scoped to the owner
drop policy if exists "resumes_all_own" on public.resumes;
create policy "resumes_all_own" on public.resumes
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ats_reports: full CRUD scoped to the owner
drop policy if exists "ats_all_own" on public.ats_reports;
create policy "ats_all_own" on public.ats_reports
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Grants (RLS still gates every row; these just let the roles reference tables).
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.profiles, public.resumes, public.ats_reports
    to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ---------------------------------------------------------------------------
-- Auto-create a profile row when a new auth user is created
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    base_username text;
    final_username text;
    n int := 0;
begin
    base_username := coalesce(
        nullif(new.raw_user_meta_data ->> 'username', ''),
        split_part(new.email, '@', 1),
        'user'
    );
    final_username := base_username;

    -- Resolve username collisions with a short random suffix.
    while exists (select 1 from public.profiles where username = final_username) loop
        n := n + 1;
        final_username := base_username || '_' || substr(md5(random()::text), 1, 5);
        exit when n > 5;
    end loop;

    insert into public.profiles (id, email, full_name, username)
    values (
        new.id,
        new.email,
        coalesce(new.raw_user_meta_data ->> 'full_name', ''),
        final_username
    )
    on conflict (id) do nothing;

    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Storage: private bucket for uploaded resume files
-- The backend writes/reads these with the service_role key (bypasses object RLS),
-- so no public policies are needed. Keeping it private is the point.
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('resumes', 'resumes', false)
on conflict (id) do nothing;
